global_gateway:
  interval: 30
  primary:
    sms: wdc
    sip: sjc
    http: sjc
  default_gateway:
    sip: sip-production-wdc.tropo.com
    sms: sip-production-wdc.tropo.com
    http: api-production-wdc.tropo.com
  responsible_domains:
    - sip.tropo.com
    - tropo1.3ccloud.com
    - sip-trunk.tropo.com
    - global-gateway.tropo.com
    - global-gateway-east.tropo.com
    - global-gateway-west.tropo.com
    - sip-trunk-global-bandwidth.tropo.com
    - sip-trunk-global-voxbone.tropo.com
    - sip-trunk-global-bandwidth.rel.tropo.com
    - sip-trunk-global-voxbone.rel.tropo.com
    - ggw1-east-prod-i.aws.tropo.com
    - ggw2-east-prod-i.aws.tropo.com
    - ggw1-west-prod-i.aws.tropo.com
    - ggw2-west-prod-i.aws.tropo.com
    - sip-trunk-jettison.tropo.com
    - sip-trunk-voxbone.tropo.com
    - sip-trunk-ipeer.tropo.com
    - sip-trunk-tata.tropo.com
    - sip-trunk-bandwidth.tropo.com
    - sip-trunk-telesmart.tropo.com
    - sip-trunk-bcbs.tropo.com
    - sip-bcbs.tropo.com
    - sip-proxy.tropo.com
    - sip-proxy-east.tropo.com
    - sip-proxy-west.tropo.com
    - sip-noproxy.tropo.com
    - jettison-proxy.tropo.com
  accounts:
    5054040:
      _comment: "qacloud1 account"
      sms:
        url: sip-production-wdc.tropo.com
      sip:
        url: sip-production-wdc.tropo.com
      http:
        url: https://api-production-wdc.tropo.com
    5002347:
      _comment: "qa_staging_wdc account"
      sms:
        url: sip-production-wdc.tropo.com
      sip:
        url: sip-production-wdc.tropo.com
      http:
        url: https://api-production-wdc.tropo.com
  ppids:
    25:
      sms: sip-production-sjc.tropo.com
      sip: sip-production-sjc.tropo.com
      http: https://api-enterprise-sjc.tropo.com
    # staging:
    #   sms: sjc
    #   sip: sjc
    #   http: sjc
  networks:
    10.160.62.64/26:
      url: https://api-staging-sjc.tropo.com
      _comment: 'subnetID: 1207983 - sjc03-shared-staging'
    10.168.49.192/26:
      url: https://api-production-sjc.tropo.com
      _comment: 'subnetID: 1212931 - sjc03-shared-production'
  staging:
    sms: sip-production-sjc.tropo.com
